export const constVariable = {
    SUCCESS : 'success',
    ERROR : 'error',
    FAILURE : 'failure',
    USERID : 'userId',
    USERNAME : 'username',
    USERTYPE : 'usertype',
    OTHERTYPE : 'othertype',
    TOKEN : 'token',
    USER : 'user',
    CLIENT : 'client',
    BEARER : 'Bearer',
    APPLICATION_JSON : 'application/json',
    UNKNOWN_ERROR : 'Unknown error!',
    ADMIN : 'admin',
    SUPERADMIN : 'superAdmin',
    EDIT : 'edit',
    ADD : 'add',
}  