export const endPoints = {
    validateUser : '/user/login',
    registerUser : '/user/signup',
    roles : '/roles',
    permission : '/permissions',
    user : '/user',
    getMe : '/user/me',
    updateMe : '/user/updateMe',
    crops : '/crops',
    cropsImage : 'uploadCropImage',
    farms : '/farms',
    surveys : '/surveys',
    cropType : '/cropTypes',
    area : '/area',
    distillery : '/distillery',
    purchase : '/purchase',
    areaNumber : '/areaNumber',
    whatsApp : '/whatsApp',
    payment : '/payment',
}